### ISSUE TITLE
Unable to install on android

### ISSUE THREAD

**Issue by neverdivideby0** [alantay11/AudiNUS#11]
When i went to your github repo on my android to download the apk, it says "There was a problem while parsing the package." It seems

**Comment by Zazazasu** [comment]
Which version of Android is your device running?

**Comment by alantay11** [comment]
Which version of Android are you using?

Can you try [this](https://github.com/alantay11/AudiNUS/releases/tag/v0.2-beta-lollipop) instead?

**Comment by neverdivideby0** [comment]
Samsung A10 on Android version 9

**Comment by neverdivideby0** [comment]
Hi i have updated my android to version 10 and now install and opening the app works however when i run a default Samsung song "Over The Horizon" the app closes unexpectantly.

Creating a playlist and the Queue works tho!

**Comment by neverdivideby0** [comment]
i have updated to android 11 and now everything works
